const { MessageEmbed } = require('discord.js')

exports.provocare = function (args) {

    const embed = new MessageEmbed().setTitle('Provocare')

    let replies = [
                    "Povestește-ne cel mai amuzant moment din viața ta.",
            "Pentru o săptămână mănâncă numai mâncare sănătoasă și pune în fiecare zi o poză pe canalul specific unde se postează poze culinare (în caz că există), o poză cu mâncarea ta.",
            "Filmează-te sau înregistrează-te cântând o cântare și trimite-ne-o.",
            "Gătește/pregătește un fel de mâncare total nou pentru tine și trimite-ne o poză.", 
            "Timp de 5 minute, vorbește bâlbâit (preferabil pe un canal de voce, ca să te auzim).",
            "Cântă-ne o cântare de copii cu tonalitate de copil.", 
            "Adu-ți un prieten aici pe comunitate.",
            "Pune @ și spune o calitate a primei persoane apărute în lista ta de tag.",
            "Azi va trebui să cânți/spui o poezie/un psalm la părtășie înainte de rugăciune. (dacă nu este porgramată o întâlnire voice pentru a avea părtășie, inițiaz-o tu!)",
            "Ține o zi de post pentru familia ta.", 
            "Povestește-ne un caz din viața ta unde Domnul a lucrat miraculos.", 
            "Fă ceva (bun) neobișnuit pentru familia ta, ceva ce nu faci de obicei, și povestește-ne reacțiile lor când au văzut.", 
            // "Vorbește cu fratele/sora mai mică despre relații, sfaturi creștinești despre alegerea partenerului potrivit (dacă este destul de mare).",  
            "Timp de o săptămână, citește câte (minim) 3 capitole din Biblie, și spune-ne cum te simți după săptămâna respectivă.",  
            "Spune-ne versetul tău preferat și de ce.", 
            "Te provoc să pui o poză cu Biblia ta și să scrii de ce e așa specială pentru tine. (nu contează unde o pui, poți pe chat sau de exemplu într-un story pe social media).", 
            "Scrie mărturia ta pe canalul #mărturii. (dacă există acest canal, dacă nu, e alegerea ta unde o faci)", 
        //    "Fă o prăjitură și pune-o pe #rețete-și-gastronomie, apoi scrie cum ai făcut-o.",  
       //     "Vineri seara va trebui să răspunzi la 3 întrebări de la Q&A!", 
       //     "Caută o nouă temă pentru Q&A (spune-o unui membru ce se ocupă cu întrebările) și scrie pe canalul #devoțional-personal de ce te fascinează tema respectivă.", 
            "Fotografiază un răsărit de soare.",
            "Învață un capitol din Biblie pe de rost.",
            "Învață o poezie creștină.",
            "Gătește un fel preferat de mâncare și pune poza pe canalul de rețete. ",
            "Postează un verset de încurajare zilnic pe BPH, timp de o săptămână. ",
            "Postează un verset la story pe Instagram/WhatsApp. ",
            "Scrie 3 motive de mulțumire pe un canal de conversații zilnice și provoacă alți 3 membri să scrie și ei mai departe. ",
            "Roagă-te timp de o săptămână, pentru persoana antipatică ție. ",
            "Desenează/colorează/pictează un desen de toamnă și postează pe canalul de artă, (dacă există). ",
            "Scrie la 3 membri de pe discord, cu care nu ai povestit niciodată. ",
            "Invită un prieten pe comunitate și integrează-l pe serverul: \n  https://discord.gg/EmPrAhm",
            "Roagă-te rugăciunea ”Tatăl nostru”, timp de o săptămână, zilnic. ",
            "Ieși în zona în care locuiești și plimbă-te. Fă 3 poze și postează pe canalul unde în care se obișnuiește să se posteze fotografii.",
            "Fă un cadou unui membru din familia ta și povestește-ne cum a reacționat.",
            "Bea 1,5 L de apă zilnic, timp de o săptămână + ceaiuri. ",
            "Fă 3000 de pași următoarea zi.",
            "Caută pe canalul dw Welcome pe cineva care e nou și ajută-l să se integreze, scriindu-i și explicându-i ce nu înțelege. (Dacă ești fată, scrie unei fete. Dacă ești băiat, scrie unui băiat.)",
        //    "Scrie o apreciere pentru un membru din echipa de organizare BPH.",
            "Scrie o apreciere pentru un membru al comunității.",
            "Promovează canalul de YouTube al Danielei Maron pe social media.",
            "Roagă-te pentru echipele de organizare BPH.",
            "Roagă-te pentru comunitatea BPH.",
            "Pune-ți ca fundal pe ecranul de blocare al telefonului o imagine pe care să scrii ”Isus te iubește!” sau un verset biblic.",
            "Du-te în parc și împarte versete biblice la persoanele spre care te călăuzește Dumnezeu.",
           // "Urează ”La mulți ani” ultimei persoane care a trimis mesaj pe canalul de #memes-posibil-creștine",
            // "Pune Discordul pe tema luminoasă, ca să vezi ce mică îmi e fața.",
            // "Deschide un ticket de moderator și mulțumește-le că nu te-au dat afară din server, încă.",
            "Ascultă pe un canal de muzică piesa ”Crocodil de Nil - Speranta pentru copii (animat)”.",
            "Spune-ne numele câinelui tău sau, dacă nu ai, atunci al pisicii tale, altfel, dacă nu ai nici aceste animăluțe, atunci numele găinii tale și dacă nici asta, atunci numele ursulețului/păpușii îndrăgite în copilărie.",
            "Ieși afară, fă o poză cu cerul acela frumos și posteaz-o pe un canal de fotografii",
            "Scrie la 8pm (20:00) pe un canal de conversații: ”Bună dimineața”. ",
            "Întreabă pe cineva (familie sau prieteni apropiați) dacă are nevoie de bani. Dacă zice că nu, zi-i atunci să ți-i dea ție pe toți.",
            // "Citește tot de pe canalul #informații-utile.",
            // "Povestește-ne despre capra cu 3 iezi pe voice.",
            "Scrie toate mesajele în silabe timp de o oră.",
            "Prețuiește persoanele dragi de aici scriindu-le câte un gând de încurajare pentru ei.",
            // "Intră pe serverul de educație și donează toate coronițele pe care le ai sau măcar jumătate.",
            "Spune-ne care a fost cea mai mică notă a ta și cum ai obținut-o.",
            "Pornește robinetul cu apă și trimite-ne o poză, pe care să scrii: ”Nu am de gând s-o opresc!”",
            "Prinde o muscă cu două degete.",
            "Participă la toate discuțiile, rugăciunile de pe voice care vor fi azi.",
            "Trimite un verset de încurajare unei persoane căreia nu i-ai mai scris niciodată. ",
            "Trimite o sugestie de provocare deținătorului meu în privat.",
            "Postează invitația pentru acest server pe grupul de tineret din care faci parte.\n  https://discord.gg/EmPrAhm",
            "Salută pe personalul de la casă (din supermarket), la plecare sau la venire, cu un salut de ”penticostali” (ex: Pacea Domnului!). ",
            "Mănâncă într-o zi numai fructe și legume crude (deci nu le gătești). Dovedește-ne cumva.",
            "Să citești Psalmul 119 pe voice într-o seară (dacă nu va mai rămâne nimeni să te asculte te poți opri, astfel completând provocarea).",
            "Dă-i cuiva nevoiaș un lucru la care ții. Poți să ne arăți cum împachetezi și cum îl dai.",
            // "Dacă tot vine iarna, prima dată când ninge la tine, du-te și stai cu picioarele goale în zăpadă. Trimite o poză.",
            "Umple-ți gura ca o veveriță și zâmbește la cameră (să ne trimiți poza cu gura ta).",
            // "Fă rost de numărul cuiva de telefon de pe discord, sună-l fără să știe că ești tu, modifică-ți vocea și înregistrează reacția lui/ei după ce află că ești tu.",
            "Să înveți un copil o cântare și să cânți pe voice cu el.",
            // "Să răspunzi la Q&A timp de 2 săptămâni.",
            "Să aduci un subiect biblic în fiecare seară pe voice timp de 3 zile.(fie voice sau în chat)",
            "Să îi trimiți un mesaj de încurajare și bun venit unui membru nou de pe server.",
            "Invită-ți un prieten nemântuit pe comunitateea:\n  https://discord.gg/EmPrAhm",
            "Invită-ți un prieten necredincios pe comunitateea:\n  https://discord.gg/EmPrAhm",
            "Invită-ți un prieten nepocăit pe comunitateea:\n  https://discord.gg/EmPrAhm",
            "Invită-ți un prieten căzut de la credință, pe comunitateea:\n  https://discord.gg/EmPrAhm",
            "Invită-ți un prieten de altă denominațiune pe comunitateea:\n  https://discord.gg/EmPrAhm",
            "Invită-ți un prieten care și-ar dori să fie pe comunitateea:\n  https://discord.gg/EmPrAhm",
            "Invită-ți un prieten deznădăjduit pe comunitateea:\n  https://discord.gg/EmPrAhm",
            "Invită-ți un prieten pe comunitateea: \n  https://discord.gg/EmPrAhm",
            "Îndeamnă pe membrii comunității, să intrați pe Voice și să vă rugați pentru comunitate și alte motive.",
            "Fă o scurtă listă cu acțiunile lui Dumnezeu care au întărit credința ta și pune-o pe un canalul de mărturii.",
            "Împarte celor din jurul tău câte un verset Biblic (colegi, cunoștințe, vecini...).",
            "Dă-i cuiva nevoiaș de mâncare.",
            "Fă 30 de genoflexiuni, 20 de flotări timp de o săptămână.",
            "Roagă-te timp de o săptămână pentru o persoană care ți-a greșit sau căreia i-ai greșit tu.",
            "Învață un psalm pe de rost și spune-l la părtășie.",
            "Învață o cântare pe de rost și cânt-o pe voce.",
            "Gătește o mâncare, pregătește un desert sau cumpără alimente pe care să le duci unei familii sărace și spune-le că Isus îi iubește.",
            "Spune celor de pe stradă, colegilor de școală sau de muncă etc despre Isus.",
            "Vizitează bătrânii de la tine din biserică și ajută-i cu treburile casnice (șters praf, curățenie, cumpărături, tăiat lemne etc) și dacă dorești și poți du-le și o mică atenție.",
            "Roagă-te, iar apoi scrie scrisori/felicitări cu mesaje de dragoste și de încurajare și distribuie oamenilor de pe stradă.",
            "Surprinde-ți părinții într-un weekend gătind pentru ei, și spunându-le cât de mult îi iubești.",
            "Fă curățenie în casă timp de o săptămână ajutându-ți mama sau surorile.",
            "Dă o geacă în condiție bună pe care tu nu o mai porți, unui cerșetor sau cerșetoare.",
            "Fă o rugăciune și scrie pe orice canal vrei: ”Dacă vezi acest mesaj, te îndemn la o rugăciune spontană. Haideți să creștem flacăra rugăciunii!„",
            
            "Să faci un lucru pe care ți-l dorești, dar pe care îl tot amâni din lipsa de timp.",
            "Stai de vorbă cu 5 cupluri căsătorite despre ce înseamnă Căsătoria.", 
            "Timp de două săptămâni, alegi 5 persoane din mediul tău cărora să le trimiți un mesaj zilnic care să le arate că le ești prieten.",
            "Fă-ți o listă cu 5 persoane de sex opus și încearcă timp de o lună. să observi minim 20 de lucruri pozitive și să le notezi.",
            "Postește o zi pe săptămână timp de 3 săptămâni",
            "Parcurge un program din cadrul Sola Scriptura.",
            "Trimite câte un verset de încurajare în ptivat la 4 persoane timp de 3 zile",
    ]
    var result = Math.floor(Math.random() * replies.length);
    
  //  const [pentru] = args
    embed.setDescription(replies[result])
//    if(pentru) embed.addField('Pentru', pentru || 'None') 
    // else embed.addField(`${message.author.tag}`)

    return embed
  }
